version: '3.6'


services:
  {{cookiecutter.project_name}}-django:
    ports:
      - '8001:8001'
    env_file:
      - ./server/env/dev.env
    volumes:
      - ./server/:/opt/{{cookiecutter.project_name}}/django
    command: bash docker/entrypoint-dev.sh

  {{cookiecutter.project_name}}-celery:
    env_file:
      - ./server/env/dev.env
    volumes:
      - ./server/:/opt/{{cookiecutter.project_name}}/django
